name: CI Status

on:
  workflow_run:
    workflows: ["Basic CI", "Check", "Test", "Lint", "MSRV"]
    types: [completed]

jobs:
  ci-status:
    name: CI Status Summary
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check workflow status
        run: |
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Status: ${{ github.event.workflow_run.conclusion }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo "✅ Workflow passed"
          elif [ "${{ github.event.workflow_run.conclusion }}" = "failure" ]; then
            echo "❌ Workflow failed"
          else
            echo "⚠️ Workflow status: ${{ github.event.workflow_run.conclusion }}"
          fi