name: Security Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run security audit daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit

      - name: Check for unsafe code
        run: |
          if find src/ -name "*.rs" -exec grep -l "unsafe" {} \; 2>/dev/null | head -1; then
            echo "::warning::Found unsafe code - please review"
            find src/ -name "*.rs" -exec grep -Hn "unsafe" {} \; 2>/dev/null || true
            exit 1
          else
            echo "✅ No unsafe code found"
          fi

      - name: Check for hardcoded secrets
        run: |
          # Look for potential secrets but exclude common false positives
          if find src/ -name "*.rs" -exec grep -l -i "password\|secret\|key\|token" {} \; 2>/dev/null | \
             xargs grep -i "password\|secret\|key\|token" 2>/dev/null | \
             grep -v "// " | grep -v "pub " | grep -v "test" | grep -v "struct" | grep -v "enum" | \
             grep -v "fn " | grep -v "let.*=" | head -1; then
            echo "::warning::Potential hardcoded secrets found - please review"
            exit 1
          else
            echo "✅ No hardcoded secrets found"
          fi